"""Added Dev model

Revision ID: 0bf1533c02f2
Revises: 2fde45834a34
Create Date: 2023-12-08 16:35:24.889176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf1533c02f2'
down_revision = '2fde45834a34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
