"""Adjusted company class

Revision ID: 3092f3474403
Revises: e9fb91def7a6
Create Date: 2023-12-08 17:27:13.717786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3092f3474403'
down_revision = 'e9fb91def7a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
