"""Corrected again relationships

Revision ID: 408ab54deff5
Revises: c82e36557bf5
Create Date: 2023-12-08 16:53:04.394544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408ab54deff5'
down_revision = 'c82e36557bf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
