"""Corrected relationships

Revision ID: c82e36557bf5
Revises: 0bf1533c02f2
Create Date: 2023-12-08 16:49:06.059614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82e36557bf5'
down_revision = '0bf1533c02f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
